---
title: "Agenda"
---

## Tuesday, August 2

- [Join the online office hours](https://purdue-edu.zoom.us/j/96788326845?pwd=VTNHRENkS3V2R3Z4VkJsMXU2ZlhFdz09
)

**Pre-workshop tutorials.** Completing the following tutorials before Wednesday will make your time with us that much more productive. 

- [R basics](r-basics.html)   
- [R chart basics](chart-basics.html)
- [R data basics](data-basics.html)


1:00--5:00 pm Eastern Time 

: *Office hours.* We are available for answering questions about MIDFIELD and resolving problems you encounter installing R or working with R in the three tutorials listed above. 

If you haven't completed the tutorials, please consider using this time on Tuesday to work on them while we are available to answer questions in real-time.  










## Wednesday, August 3

- [Join the online meeting](https://purdue-edu.zoom.us/j/96788326845?pwd=VTNHRENkS3V2R3Z4VkJsMXU2ZlhFdz09
)

1:00--2:00 Eastern Time

: *Introductions.* Introduce facilitators and participants, objectives, and  MIDFIELD.

2:00--3:00

: *Exploring data structure.* Exploring data excerpts manually.

3:00--5:00 

: *Guided practice.* Self-paced case study using midfieldr and midfielddata. Real-time help. 

- [Case study: Goals](https://midfieldr.github.io/midfieldr/articles/art-001-case-goals.html) A short reading.   
- [Case study: Data](https://midfieldr.github.io/midfieldr/articles/art-002-case-data.html) A midfieldr tutorial. 

Please check in with us before leaving the virtual meeting. 

**Homework**

- Complete the guided practice "Data" tutorial. 
- *Optional (FYI)*. Topics from today's guided practice are developed in greater detail in midfieldr package vignettes  [[link]](https://midfieldr.github.io/midfieldr/articles/).






## Thursday, August 4

- [Join the online meeting](https://purdue-edu.zoom.us/j/96788326845?pwd=VTNHRENkS3V2R3Z4VkJsMXU2ZlhFdz09
)

1:00--1:30 Eastern Time

: *Metaphors and metrics.* Pipelines, pathways, and ecosystems.


1:30--2:30

: *Guided practice.* Continue the case study.

- [Case study: Results](https://midfieldr.github.io/midfieldr/articles/art-003-case-results.html) A midfieldr tutorial. 


2:30--3:30

: *Data visualization session 1* 

- [Creating more effective charts](effective-charts.html) Introduction. 
- [Download PDF](https://github.com/graphdr/workshop-data-stories/blob/main/slides/effective-charts-handout.pdf) worksheets for think-write-share activities. Hard copy seems to work best for many people.  

3:30--5:00 

: *Operationalizing a research question.* Define a problem in the data that interests you with our assistance, form small groups. Report out your research questions and discussion. 

- [Data dictionaries](https://midfieldr.github.io/midfielddata/reference/index.html) for the four practice data sets. 
- [Exploring the variables](https://midfieldr.github.io/midfieldr/articles/art-000-getting-started.html) using R. The midfieldr "Getting started" page illustrates how to examine possible values for a variable.  


Please check in with us before leaving the virtual meeting. 

**Homework**

- Complete the guided practice "Results" tutorial. 
- Refine your plan for working on your research question.  
- *Optional (FYI)*. Topics from today's guided practice are developed in greater detail in midfieldr package vignettes  [[link]](https://midfieldr.github.io/midfieldr/articles/).






## Friday, August 5

- [Join the online meeting](https://purdue-edu.zoom.us/j/96788326845?pwd=VTNHRENkS3V2R3Z4VkJsMXU2ZlhFdz09
)

1:00--2:00 Eastern Time

: *Data visualization session 2*

- [Expanding your graphical repertoire](chart-repertoire.html) Introduction. 
- [Download PDF](https://github.com/graphdr/workshop-data-stories/blob/main/slides/chart-repertoire-handout.pdf) worksheets for think-write-share activities. Hard copy seems to work best for many people. 

2:00--3:30 

: *Work on your research question.* Consult with us on your progress, discussion 

3:30--4:30

: *Progress report* shared with the group. 

4:40--4:45

: *Wrap up.*





