---
title: "New to R"
---

To get the most out of the workshop, you should have the essential software installed and running several days before the workshop to give you time to contact us with questions if anything goes amiss.

If you are trying R for the first time, it is vital that you attempt to set up your computer with the necessary software in advance or it will be difficult to keep up. 

## Already installed?

If you do not have R and RStudio installed, please skip this section and start with the next section. 

If you are already an R and RStudio user, this is a great time to check for updates. 

**Updating RStudio**

- RStudio menu *Help \> Check for Updates* will tell you if you are current or not. 
- To update, close RStudio on your machine, download the new version from the [RStudio website](https://www.rstudio.com/products/rstudio/#Desktop), and run the `RStudio-some-version-number.exe`. (Windows users *might* have to run the executable as an administrator.)

**Update your packages**

[How to upgrade all out-of-date packages](https://rstats.wtf/maintaining-r.html#how-to-upgrade-all-out-of-date-packages) in *What They Forgot to Teach You About R* by Jennifer Bryan and Jim Hester. 


**Updating R**

The easiest way to update R is to simply [download the newest version](https://cloud.r-project.org/). RStudio will automatically use the latest you've installed. 


Alternatively, Windows users can use the installr package:

- Install the installr package 
- If open, close R and RStudio 
- Navigate to your most recent `Rgui.exe` file located in your Programs directory, e.g., `C:\Program Files\R\R-4.0.0\bin\x64\Rgui.exe`  
- Right-click on `Rgui.exe` and run as administrator
- In the R GUI window that appears, run the commands

``` r
    # Windows users only
    library("installr")
    updateR()
```

**Updating your R library**

[How to transfer your library when updating R](https://rstats.wtf/maintaining-r.html#how-to-transfer-your-library-when-updating-r) also by Bryan and Hester. Requires the fs package.  


## Install R and RStudio 

This section is for anyone who has not yet installed R or RStudio. 

The first steps are to install R and RStudio. Windows users may have to login as an Administrator before installing the software. 

- [Install R](https://cloud.r-project.org) for your operating system  
- [Install RStudio](https://www.rstudio.com/products/rstudio/download/#download), a user interface for R


Once the installation is complete, you can take a 2-minute tour of the RStudio interface.

- [Let's start (00:57--02:32)](https://www.youtube.com/embed/kfcX5DEMAp4?start=57&end=152) by R Ladies Sydney [@RLadiesSydney:2018:Lesson1]   

The same video includes a longer (7 minute) tour of the four quadrants (panes) in RStudio if you are interested. 

- [The RStudio quadrants (07:21--14:40)](https://www.youtube.com/embed/kfcX5DEMAp4?start=441&end=880) by R Ladies Sydney [@RLadiesSydney:2018:Lesson1] 

